In [53]:
import pandas as pd
import numpy as np

In [54]:
df = pd.read_csv(r"D:\NeuralStock\data\raw\ecommerce_inventory_demand.csv")

In [55]:
df.head()

,date,product_id,product_category,units_sold,unit_price,stock_on_hand,reorder_point,is_promotion,discount_pct,day_of_week,month,supplier_lead_days
0,2022-06-27,P006,Electronics,NaN,10225.02,203,79,0,0.0,0,6,13
1,2023-06-14,P028,Apparel,NaN,1137.33,108,51,0,0.0,2,6,8
2,2022-06-20,P005,Electronics,NaN,8245.58,274,72,0,0.0,0,6,9
3,2022-03-06,P039,Home,NaN,2657.76,179,43,0,0.0,6,3,12
4,2022-05-01,P015,Electronics,NaN,12117.51,205,52,0,0.0,6,5,8

In [56]:
df.tail()

,date,product_id,product_category,units_sold,unit_price,stock_on_hand,reorder_point,is_promotion,discount_pct,day_of_week,month,supplier_lead_days
6218,2023-03-14,P034,Sports,21.0,2401.48,147,52,0,0.0,1,3,2
6219,2023-08-29,P013,Beauty,49.0,2340.86,92,77,0,0.0,1,8,10
6220,2023-09-03,P026,Home,16.0,7493.60,100,42,0,0.0,6,9,8
6221,2023-09-23,P017,Electronics,31.0,19315.04,142,59,0,0.0,5,9,7
6222,2022-04-10,P007,Electronics,14.0,14686.62,82,60,0,0.0,6,4,14

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6223 entries, 0 to 6222
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                6223 non-null   object
 1   product_id          6223 non-null   object
 2   product_category    6223 non-null   object
 3   units_sold          5974 non-null   float64
 4   unit_price          6223 non-null   float64
 5   stock_on_hand       6223 non-null   int64
 6   reorder_point       6223 non-null   int64
 7   is_promotion        6223 non-null   int64
 8   discount_pct        6223 non-null   float64
 9   day_of_week         6223 non-null   int64
 10  month               6223 non-null   int64
 11  supplier_lead_days  6223 non-null   int64
dtypes: float64(3), int64(6), object(3)
memory usage: 583.5+ KB

In [58]:
df.describe()

,units_sold,unit_price,stock_on_hand,reorder_point,is_promotion,discount_pct,day_of_week,month,supplier_lead_days
count,5974.000000,6223.000000,6223.000000,6223.000000,6223.000000,6223.000000,6223.000000,6223.000000,6223.000000
mean,28.372782,9153.228877,122.621887,49.014945,0.056886,1.953736,3.018801,6.470673,8.268038
std,14.032411,16741.874355,72.709263,17.514845,0.231643,8.645728,2.001880,3.464853,3.744854
min,5.000000,705.520000,-365.000000,20.000000,0.000000,0.000000,0.000000,1.000000,2.000000
25%,19.000000,2011.130000,72.000000,36.000000,0.000000,0.000000,1.000000,3.000000,5.000000
50%,25.000000,4863.620000,111.000000,51.000000,0.000000,0.000000,3.000000,6.000000,8.000000
75%,34.000000,13299.370000,165.000000,60.000000,0.000000,0.000000,5.000000,9.000000,12.000000
max,158.000000,246143.800000,387.000000,79.000000,1.000000,60.000000,6.000000,12.000000,14.000000

In [59]:
df.isnull().sum()

date                    0
product_id              0
product_category        0
units_sold            249
unit_price              0
stock_on_hand           0
reorder_point           0
is_promotion            0
discount_pct            0
day_of_week             0
month                   0
supplier_lead_days      0
dtype: int64

In [60]:
df['date'] = pd.to_datetime(df['date'])

In [61]:
df = df.sort_values(['product_id', 'date']).reset_index(drop=True)

In [ ]:
df['units_sold'] = df.groupby('product_id')['units_sold'].ffill()

In [63]:
df['units_sold'].isnull().sum()

np.int64(3)

In [64]:
df[df['stock_on_hand']<0]

,date,product_id,product_category,units_sold,unit_price,stock_on_hand,reorder_point,is_promotion,discount_pct,day_of_week,month,supplier_lead_days
118,2023-07-21,P001,Electronics,15.0,24163.18,-103,45,0,0.0,4,7,13
217,2023-02-16,P002,Sports,17.0,5506.40,-199,55,0,0.0,3,2,9
264,2023-11-18,P002,Sports,34.0,5630.07,-154,55,0,0.0,5,11,9
322,2022-09-12,P003,Home,29.0,4953.25,-142,79,0,0.0,0,9,10
378,2023-08-17,P003,Home,20.0,4933.87,-170,79,0,0.0,3,8,10
...,...,...,...,...,...,...,...,...,...,...,...,...
5996,2022-06-25,P049,Apparel,38.0,1171.70,-48,23,0,0.0,5,6,8
6040,2023-03-25,P049,Apparel,41.0,1124.69,-66,23,0,0.0,5,3,8
6078,2023-10-15,P049,Apparel,84.0,1125.69,-42,23,1,30.5,6,10,8
6170,2023-02-16,P050,Electronics,12.0,18981.45,-114,78,0,0.0,3,2,2
6190,2023-05-11,P050,Electronics,15.0,19136.29,-153,78,0,0.0,3,5,2

In [65]:
group_means = df.groupby('product_id')['stock_on_hand'].transform('mean')

In [66]:
df['stock_on_hand']=np.where(df['stock_on_hand']<0, group_means, df['stock_on_hand'])

In [ ]:
df_encoded = pd.get_dummies(df['product_category'],drop_first=False)

In [68]:
df.drop('product_category', axis=1, inplace=True)

In [69]:
df = pd.concat([df, df_encoded], axis=1)

In [70]:
target_cols=["Beauty", "Electronics", "Home", "Sports"]
for col in target_cols:
    df[col] = df[col].astype(int)

In [71]:
Q1 = df['unit_price'].quantile(0.25)
Q3 = df['unit_price'].quantile(0.75)
IQR = Q3 - Q1

In [72]:
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

In [73]:
df['unit_price'] = df['unit_price'].clip(lower=lower_bound, upper=upper_bound)

In [74]:
df['day_sin'] = np.sin(2 * np.pi * df['day_of_week'] / 7)
df['day_cos'] = np.cos(2 * np.pi * df['day_of_week'] / 7)

In [ ]:
df['month_sin'] = np.sin(2 * np.pi * df['month'] / 12)
df['month_cos'] = np.cos(2 * np.pi * df['month'] / 12)

In [ ]:
df['unit_price'].describe()

count     6223.000000
mean      7962.487390
std       7445.897294
min        705.520000
25%       2011.130000
50%       4863.620000
75%      13299.370000
max      30231.730000
Name: unit_price, dtype: float64

In [ ]:
df.to_csv('../data/processed/processed_data.csv', index=False)